"""Unit tests for ru_pulse.voice_lint.

Run:
    python -m pytest ru_pulse/tests/test_voice_lint.py -v

These tests require a populated `ru_pulse/reports/voice_fingerprint.json`,
generated by running `python -m ru_pulse.voice_fingerprint` against a
fetched corpus. In the public OSS distribution that fixture file is
intentionally absent (it bakes in private channel data); the tests
skip cleanly in that case. The exception-path test below explicitly
covers the missing-file case.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

RESEARCH_DIR = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(RESEARCH_DIR))

from ru_pulse.voice_lint import lint, LintResult, _FP_PATH

pytestmark = pytest.mark.skipif(
    not _FP_PATH.exists(),
    reason="voice_fingerprint.json absent (run `python -m ru_pulse.voice_fingerprint` first)",
)


HYPE_TEXT = (
    "ТОП 10 НЕЙРОСЕТЕЙ 2026\n"
    "- CHATGPT — ЛУЧШИЙ\n"
    "- GEMINI — ВТОРОЙ\n"
    "- CLAUDE — ТРЕТИЙ\n"
    "- GROK — ЧЕТВЕРТЫЙ\n"
    "- LLAMA — ПЯТЫЙ\n"
    "- MISTRAL — ШЕСТОЙ\n"
    "- DEEPSEEK — СЕДЬМОЙ\n"
    "- PHI — ВОСЬМОЙ\n"
    "- COMMAND — ДЕВЯТЫЙ\n"
    "- QWEN — ДЕСЯТЫЙ\n"
    "ИСПОЛЬЗУЙТЕ ПРЯМО СЕЙЧАС. БЕСПЛАТНО."
)

FIRST_PERSON_LONG = (
    "Я провёл три недели, настраивая собственный AI-pipeline на дешёвых VPS.\n"
    "Сначала я взял OpenRouter — подключил Haiku, запустил первые тесты.\n"
    "Потом я обнаружил, что мой промпт-кэш сжирает $12 в день без пользы.\n"
    "Я переписал систему: добавил дедупликацию, сократил контекст с 32k до 8k.\n"
    "Мой результат: $47 в месяц вместо $180. Вот конкретные числа из лога.\n"
    "Я рекомендую не копировать чужие setup-ы — замеряйте свой трафик сначала.\n"
    "Это не теория. Я живу на этой инфре каждый день в Тель-Авиве.\n"
    "Если вам интересно, мой конфиг лежит в репозитории — ссылка ниже.\n"
    "Что я понял: одиночка может держать серьёзный стек за $50/мес.\n"
    "Нужно только убрать жир и мерить. Я написал скрипт для этого — покажу.\n"
)

BROADCAST_TEXT = (
    "OpenAI выпустила обновление для GPT-4o. "
    "Теперь модель поддерживает мультимодальный ввод без дополнительных настроек. "
    "Анонс опубликован на официальном сайте компании. "
    "Обновление доступно всем пользователям платного тарифа. "
    "Технические характеристики: контекст 128k, задержка снижена на 30%."
)

LISTICLE_TEXT = (
    "5 инструментов для соло-фаундера:\n"
    "1. n8n — автоматизация без кода\n"
    "2. Postiz — планировщик контента\n"
    "3. OpenRouter — единый API для LLM\n"
    "4. Supabase — база данных\n"
    "5. Vercel — деплой за секунды\n"
)

SHORT_TEXT = "ок"
EMPTY_TEXT = ""


def test_hype_text_high_hype_score():
    result = lint(HYPE_TEXT)
    assert result.hype_score > 0.6, (
        f"hype_score={result.hype_score} expected >0.6 for all-caps bullet post"
    )


def test_hype_text_returns_full_result():
    result = lint(HYPE_TEXT)
    assert isinstance(result, LintResult)
    assert len(result.nearest_buckets) == 3
    assert len(result.nearest_channels) == 5


def test_first_person_long_lands_personal_bucket():
    result = lint(FIRST_PERSON_LONG)
    top_bucket = result.nearest_buckets[0].bucket
    assert top_bucket in ("ai_core", "indie_solo", "prompt_specific"), (
        f"Expected personal bucket, got {top_bucket}"
    )


def test_first_person_low_broadcast():
    result = lint(FIRST_PERSON_LONG)
    assert result.broadcast_score < 0.7, (
        f"broadcast_score={result.broadcast_score} should be lower for first-person post"
    )


def test_empty_text_no_crash():
    result = lint(EMPTY_TEXT)
    assert isinstance(result, LintResult)
    assert result.verdict


def test_short_text_no_crash():
    result = lint(SHORT_TEXT)
    assert isinstance(result, LintResult)
    assert len(result.nearest_buckets) == 3


def test_short_json_serializable():
    result = lint(SHORT_TEXT)
    parsed = json.loads(result.to_json())
    assert "verdict" in parsed
    assert "nearest_buckets" in parsed


def test_broadcast_text_high_broadcast_score():
    result = lint(BROADCAST_TEXT)
    assert result.broadcast_score > 0.6, (
        f"broadcast_score={result.broadcast_score} expected >0.6 for impersonal news post"
    )


def test_listicle_text_listicle_score():
    result = lint(LISTICLE_TEXT)
    assert result.listicle_hits >= 1, (
        f"listicle_hits={result.listicle_hits} expected >=1 for numbered list post"
    )
    assert isinstance(result.listicle_hits, int)


def test_listicle_buckets_populated():
    result = lint(LISTICLE_TEXT)
    assert len(result.nearest_buckets) == 3
    for b in result.nearest_buckets:
        assert b.distance >= 0.0


def test_lint_with_empty_corpus_returns_unknown_verdict(monkeypatch):
    """Guard against IndexError when fingerprint corpus has no buckets."""
    from ru_pulse import voice_lint as vl
    empty_corpus = {"raw": [], "normalized": [], "bucket_centroids": {}}
    monkeypatch.setattr(vl, "_CORPUS", empty_corpus)
    result = vl.lint("any text")
    assert result.nearest_buckets == []
    assert result.nearest_channels == []
    assert "no buckets" in result.verdict.lower() or result.verdict


def test_load_corpus_missing_file_raises(monkeypatch, tmp_path):
    """Helpful error when fingerprint JSON not yet generated."""
    from ru_pulse import voice_lint as vl
    monkeypatch.setattr(vl, "_CORPUS", None)
    monkeypatch.setattr(vl, "_FP_PATH", tmp_path / "nonexistent.json")
    import pytest
    with pytest.raises(FileNotFoundError) as exc:
        vl._load_corpus()
    assert "voice_fingerprint" in str(exc.value)
